### ISSUE TITLE
pop from empty list

### ISSUE THREAD

**Issue by TRONBFFL** [aigc-apps/VideoX-Fun#73]
Was trying a Lora (maybe I am using the wrong one) but the two I tried received "pop from empty list" error. Thoughts?

I tried these both (BTW the workflow works without using the Lora)
https://huggingface.co/DylanDDeng/cogvideo-lora-v1/
https://huggingface.co/ECNU-CILab/ExVideo-CogVideoX-LoRA-129f-v1

Error loading layer
!!! Exception during processing !!! pop from empty list
Traceback (most recent call last):
  File "C:\comf2\ComfyUI\custom_nodes\CogVideoX-Fun\cogvideox\utils\lora_utils.py", line 396, in merge_lora
    curr_layer = curr_layer.__getattr__(temp_name)
  File "C:\comf2\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 155, in __getattr__
    return super().__getattr__(name)
  File "C:\comf2\venv\lib\site-packages\torch\nn\modules\module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'CogVideoXTransformer3DModel' object has no attribute 'transformer'

**Comment by bubbliiiing** [comment]
Sorry, these Loras seem to have been prepared for the original [CogVideoX](https://github.com/THUDM/CogVideo), not CogVideoX Fun, so they cannot be loaded.

**Comment by TRONBFFL** [comment]
ah ok I see, well that's not "fun" :) - are there loras that work with CogVideoX Fun?

Side question - what do you think Hailou.video is using Cogvideo or something else?

**Comment by bubbliiiing** [comment]
Like this https://huggingface.co/MoonShinkiro/cogvideox-5b-fun-lora-bladerunnerv1 ?
Hailou-video is a close source model, definitely not CogVideo.
